export const DOMAIN_QUESTIONS: Record<string, string[]> = {
  Social: [
    "How often does the child avoid looking at people's faces while talking or playing?",
    'How often does the child not smile back when someone smiles at them?',
    'How often does the child prefer to stay alone instead of joining family members or other children?',
    'How often does the child not seek help, comfort, or share excitement with a familiar person?',
    'How often does the child seem unaware of people around them?',
    'How often does the child not notice or join what other people are doing?',
    'How often does the child play alone in the same way again and again?',
    'How often does the child have difficulty waiting for their turn during play or conversation?',
    'How often does the child avoid playing or interacting with other children of a similar age?',
  ],
  Emotion: [
    'How often does the child react in a way that does not match the situation?',
    'How often does the child react much more strongly than the situation requires?',
    'How often does the child suddenly laugh, cry, or become excited without an obvious reason?',
    'How often does the child do dangerous things without seeming to understand the risk?',
    'How often does the child suddenly become very excited or upset without an obvious reason?',
  ],
  Speech: [
    'How often does the child stop using words or sentences they could previously say?',
    'How often does the child find it difficult to use gestures like pointing, waving, or nodding to communicate?',
    'How often does the child repeat the same words or phrases again and again?',
    'How often does the child repeat words or questions exactly as they hear them?',
    'How often does the child make unusual sounds instead of using words?',
    'How often does the child have difficulty starting or continuing a conversation?',
    'How often does the child use words that do not have a clear meaning to others?',
    'How often does the child refer to themselves using the wrong words, such as saying "you" instead of "I"?',
    'How often does the child have difficulty understanding the real meaning behind what others say.',
  ],
  Behavior: [
    'How often does the child repeatedly flap their hands, rock their body, spin, or make the same movements again and again?',
    'How often does the child become unusually attached to a particular object?',
    'How often does the child seem unable to sit still or stay calm?',
    'How often does the child hit, kick, bite, push, or hurt others?',
    'How often does the child have intense tantrums that are difficult to calm?',
    'How often does the child hurt themselves on purpose?',
    'How often does the child become upset when daily routines or familiar things change?',
  ],
  Sensory: [
    'How often does the child react strongly to everyday sounds, lights, smells, touch, or certain clothes?',
    'How often does the child stare into space for a long time without responding?',
    'How often does the child have difficulty following a moving object with their eyes?',
    'How often does the child look at objects in unusual ways?',
    'How often does the child seem to feel little or no pain after getting hurt?',
    'How often does child repeatedly smell objects, put things in their mouth, or frequently touch people?',
  ],
  Cognitive: [
    'How often does the child have difficulty staying focused on an activity?',
    'How often does the child take much longer than expected to respond when spoken to?',
    'How often does the child remember unusual details much better than expected?',
    'How often does the child show an exceptional skill that is much stronger than expected for their age?',
  ],
};
